version: '3.8'

services:
  simulator:
    build:
      context: ./simulator
      dockerfile: Dockerfile
    container_name: simulator
    depends_on:
      - model
    environment:
        ENDPOINT: "http://model:5001/predict"
    networks:
      - maintenance-net

  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    container_name: model
    ports: 
      - "5001:5001"
    networks:
      - maintenance-net

networks:
  maintenance-net:
    driver: bridge

