version: '3.8'

services:
  simulator:
    build:
      context: ./simulator
      dockerfile: Dockerfile
    container_name: simulator
    depends_on:
      model:
        condition: service_healthy  
    environment:
      ENDPOINT: "http://model:5001/predict"
      HEALTHENDPOINT: "http://model:5001/health"
    networks:
      - maintenance-net

  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    container_name: model
    ports:
      - "5001:5001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    environment:
      USINGQUEUE: True
      HEALTHENDPOINT: ""
    networks:
      - maintenance-net

networks:
  maintenance-net:
    driver: bridge

